root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/lw ./cmd/lw"
  entrypoint = "./tmp/lw"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]
  kill_delay = "0s"
  rerun = false
  rerun_delay = 500

[log]
  main_only = true
  time = false

[misc]
  clean_on_exit = true
